name: lab08
runtime: yaml
description: Deploy a static website using S3 and CloudFront with Pulumi YAML

resources:
  myBucket:
    type: aws:s3:BucketV2

  myBucketPublicAccess:
    type: aws:s3:BucketPublicAccessBlock
    properties:
      bucket: ${myBucket.id}
      blockPublicAcls: false
      blockPublicPolicy: false
      ignorePublicAcls: false
      restrictPublicBuckets: false

  myBucketWebsite:
    type: aws:s3:BucketWebsiteConfigurationV2
    properties:
      bucket: ${myBucket.id}
      indexDocument:
        suffix: index.html
      errorDocument:
        key: error.html

  myBucketPolicy:
    type: aws:s3:BucketPolicy
    properties:
      bucket: ${myBucket.id}
      policy: ${jsonencode({
        "Version": "2012-10-17",
        "Statement": [{
          "Effect": "Allow",
          "Principal": "*",
          "Action": "s3:GetObject",
          "Resource": "arn:aws:s3:::${myBucket.id}/*"
        }]
      })}

  myCloudFrontOAC:
    type: aws:cloudfront:OriginAccessControl
    properties:
      name: my-oac
      description: "CloudFront OAC for S3"
      originAccessControlOriginType: "s3"
      signingBehavior: "always"
      signingProtocol: "sigv4"

  myCloudFrontDistribution:
    type: aws:cloudfront:Distribution
    properties:
      enabled: true
      defaultRootObject: index.html
      origins:
        - domainName: ${myBucket.bucketRegionalDomainName}
          originAccessControlId: ${myCloudFrontOAC.id}
          s3OriginConfig: {}
      defaultCacheBehavior:
        viewerProtocolPolicy: "redirect-to-https"
        allowedMethods: ["GET", "HEAD"]
        cachedMethods: ["GET", "HEAD"]
        targetOriginId: ${myBucket.id}
        forwardedValues:
          queryString: false
          cookies:
            forward: "none"
      priceClass: "PriceClass_100"
      viewerCertificate:
        cloudfrontDefaultCertificate: true

outputs:
  bucketName: ${myBucket.id}
  cloudFrontURL: https://${myCloudFrontDistribution.domainName}

config:
  pulumi:tags:
    value:
      pulumi:template: aws-yaml
