name: Deploy Static Website with Pulumi

on:
  push:
    branches:
      - main  # Adjust to your branch name if needed

jobs:
  pulumi-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v3

      - name: Login to Pulumi
        run: pulumi login --cloud-url https://app.pulumi.com

      - name: Select Pulumi stack
        run: pulumi stack select lab08/deve

      - name: Deploy infrastructure
        run: pulumi up --yes

  pulumi-destroy:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'  # Allows manual trigger for destruction

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Pulumi CLI
        uses: pulumi/setup-pulumi@v3

      - name: Login to Pulumi
        run: pulumi login --cloud-url https://app.pulumi.com

      - name: Select Pulumi stack
        run: pulumi stack select lab08/deve

      - name: Destroy infrastructure
        run: pulumi destroy --yes
