name: Deploy Static Website with Pulumi

on:
  push:
    branches:
      - main  # Adjust if needed
  workflow_dispatch:  # Allows manual trigger

jobs:
  pulumi-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pulumi CLI
        uses: pulumi/actions@v5  # ✅ Correct Pulumi action

      - name: Login to Pulumi
        run: pulumi login --cloud-url https://app.pulumi.com

      - name: Select Pulumi stack
        run: pulumi stack select lab08/deve

      - name: Deploy infrastructure
        run: pulumi up --yes

  pulumi-destroy:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'  # Manual trigger

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pulumi CLI
        uses: pulumi/actions@v5  # ✅ Correct Pulumi action

      - name: Login to Pulumi
        run: pulumi login --cloud-url https://app.pulumi.com

      - name: Select Pulumi stack
        run: pulumi stack select lab08/deve

      - name: Destroy infrastructure
        run: pulumi destroy --yes
