name: main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pulumi-up:
    name: pulumi-up
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: ./ppinfra
        run: npm install

      - name: Set PULUMI_ACCESS_TOKEN
        run: echo "PULUMI_ACCESS_TOKEN=${{ secrets.PULUMI_ACCESS_TOKEN }}" >> $GITHUB_ENV  # Ensure token is available globally

      - name: Set AWS Region
        run: pulumi config set aws:region us-east-1  # Set AWS region

      - name: Select Pulumi Stack
        run: pulumi stack select uakanksha/lab08/deve  # Select the stack

      - name: Run Pulumi Up
        uses: pulumi/actions@v5
        with:
          command: up
          stack-name: uakanksha/lab08/deve  # Use your stack name here
          work-dir: ./ppinfra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
